version: '3.5'
services:
  notion-next:
    container_name: notion-next
    image: fgprodigal/notion-next:latest
    restart: unless-stopped
    networks:
      network:
        ipv4_address: 172.25.0.2

networks:
  network:
    ipam:
      config:
        - subnet: 172.25.0.0/24